-- Quotes from Civilization VI, formatted by Mattson42 (issue 464).
-- Copy this file into settings/bookshelf/quotes to use it.
return {
    { q = "It is not wisdom but authority that makes a law.", a = "Thomas Hobbes", b = "A Dialogue Between a Philosopher and a Student of the Common Laws of England" },
    { q = "At his best, man is the noblest of all animals; separated from law and justice he is the worst.", a = "Aristotle", b = "Politics" },
    { q = "Without craftsmanship, inspiration is a mere reed shaken in the wind.", a = "Johannes Brahms", b = "Personal Correspondence" },
    { q = "Skill without imagination is craftsmanship and gives us many useful objects such as wickerwork picnic baskets.", a = "Tom Stoppard", b = "Artist Descending a Staircase" },
    { q = "Every nation lives by exchanging.", a = "Adam Smith", b = "The Wealth of Nations" },
    { q = "That’s the positive aspect of trade I suppose. The world gets stirred up together.", a = "Isabel Hoving", b = "The Dream Merchant" },
    { q = "Bravery is being the only one who knows you’re afraid.", a = "Colonel David Hackworth", b = "About Face: The Odyssey of an American Warrior" },
    { q = "I don’t underrate the value of military knowledge, but if men make war in slavish obedience to rules, they will fail.", a = "Ulysses S. Grant", b = "Personal Memoirs" },
    { q = "A strong economy begins with a strong, well-educated workforce.", a = "Bill Owens", b = "Public Address" },
    { q = "It is equally important to have a happy and engaged workforce as it is to have a profitable bottom line.", a = "Vern Dosch", b = "Wired Differently" },
    { q = "Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too.", a = "Marcus Aurelius", b = "Meditations" },
    { q = "It was luxuries like air conditioning that brought down the Roman Empire. With air conditioning their windows were shut; they couldn’t hear the barbarians coming.", a = "Garrison Keillor", b = "Lake Wobegon Days" },
    { q = "Mysticism is the mistake of an accidental and individual symbol for a universal one.", a = "Ralph Waldo Emerson", b = "Essays: Second Series" },
    { q = "I like to say I practice militant mysticism. I’m absolutely sure of some things that I don’t quite know.", a = "Rob Bell", b = "Velvet Elvis: Repainting the Christian Faith" },
    { q = "If bread is the first necessity of life, recreation is a close second.", a = "Edward Bellamy", b = "The Duke of Stockbridge" },
    { q = "People who cannot find time for recreation are sooner or later to find time for illness.", a = "John Wanamaker", b = "Public Address" },
    { q = "Politics is the art of the possible, the attainable – the art of the next best.", a = "Otto von Bismarck", b = "Interview with Meyer von Waldeck (1867)" },
    { q = "Divide and rule, a sound motto. Unite and lead, a better one.", a = "Johann Wolfgang von Goethe", b = "Gedichte" },
    { q = "The poets have been mysteriously silent on the subject of cheese.", a = "G. K. Chesterton", b = "Alarms and Discursions" },
    { q = "All the world’s a stage, and all the men and women merely players.", a = "William Shakespeare", b = "As You Like It" },
    { q = "If it’s natural to kill, how come men have to go into training to learn how?", a = "Joan Baez", b = "Daybreak" },
    { q = "Those who in quarrels interpose, must often wipe a bloody nose.", a = "John Gay", b = "Fables" },
    { q = "Invincibility lies in the defense; the possibility of victory in the attack.", a = "Sun Tzu", b = "The Art of War" },
    { q = "Defense is superior to opulence.", a = "Adam Smith", b = "The Wealth of Nations" },
    { q = "I've lived through some terrible things in my life, some of which actually happened.", a = "Mark Twain", b = "Attributed" },
    { q = "History is the version of past events that people have decided to agree upon.", a = "Napoleon Bonaparte", b = "Maxims" },
    { q = "We can no more have exact religious thinking without theology, than exact mensuration and astronomy without mathematics, or exact iron-making without chemistry.", a = "John Hall", b = "Sermon / Public Address" },
    { q = "Man suffers only because he takes seriously what the gods made for fun.", a = "Alan W. Watts", b = "Out of Your Mind" },
    { q = "A good navy is not a provocation to war. It is the surest guaranty of peace.", a = "Theodore Roosevelt", b = "Annual Message to Congress (1902)" },
    { q = "The Navy has both a tradition and a future – and we look with pride and confidence in both directions.", a = "Arleigh Burke", b = "Public Address" },
    { q = "In democracy it’s your vote that counts; in feudalism it’s your count that votes.", a = "Mogens Jallberg", b = "Attributed" },
    { q = "With the advance of feudalism came the growth of iron armor, until, at last, a fighting-man resembled an armadillo.", a = "John Boyle O’Reilly", b = "Attributed" },
    { q = "It’s all papers and forms, the entire civil service is like a fortress made of papers, forms and red tape.", a = "Alexander Ostrovsky", b = "The Diary of a Scoundrel" },
    { q = "The taxpayer - that's someone who works for the federal government but doesn't have to take the civil service examination.", a = "Ronald Reagan", b = "Public Address" },
    { q = "In peace one is despoiled by mercenaries; in war by one’s enemies.", a = "Niccolo Machiavelli", b = "The Prince" },
    { q = "Being a mercenary, though … Hey, we just go wherever there’s a mixture of money and trouble.", a = "Howard Tayler", b = "Schlock Mercenary" },
    { q = "All that glisters is not gold; often have you heard that told.", a = "William Shakespeare", b = "The Merchant of Venice" },
    { q = "There are very honest people who do not think that they have had a bargain unless they have cheated a merchant.", a = "Anatole France", b = "The Crime of Sylvestre Bonnard" },
    { q = "Every man should make his son learn some useful trade or profession, so that in these days of changing fortunes … they may have something tangible to fall back upon.", a = "Phineas T. Barnum", b = "The Art of Money Getting" },
    { q = "You can’t go around arresting the Thieves’ Guild. I mean, we’d be at it all day!", a = "Terry Pratchett", b = "Guards! Guards!" },
    { q = "I conclude then this point touching upon the power of kings with this axiom of divinity, That as to dispute what God may do is blasphemy … so it is sedition to dispute what a king may do.", a = "King James I", b = "Speech to Parliament (1610)" },
    { q = "Listen, strange women lying in ponds distributing swords is no basis for a system of government … You can’t expect to wield supreme power just ‘cause some watery tart threw a sword at you!", a = "Monty Python", b = "Monty Python and the Holy Grail" },
    { q = "The day we stop exploring is the day we commit ourselves to live in a stagnant world, devoid of curiosity, empty of dreams.", a = "Neil deGrasse Tyson", b = "Space Chronicles: Facing the Ultimate Frontier" },
    { q = "We shall not cease from exploration, and the end of all our exploring will be to arrive where we started and know the place for the first time.", a = "T.S. Eliot", b = "Four Quartets: Little Gidding" },
    { q = "The four characteristics of humanism are curiosity, a free mind, belief in good taste, and belief in the human race.", a = "E.M. Forster", b = "Two Cheers for Democracy" },
    { q = "You must not lose faith in humanity. Humanity is like an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.", a = "Mahatma Gandhi", b = "Letter to Rajkumari Amrit Kaur (1941)" },
    { q = "In diplomacy there are two kinds of problems: small ones and large ones. The small ones will go away by themselves, and the large ones you will not be able to do anything about.", a = "Patrick McGuinness", b = "The Last Hundred Days" },
    { q = "A diplomat is a man who always remembers a woman’s birthday but never remembers her age.", a = "Robert Frost", b = "Attributed" },
    { q = "I don't like to commit myself about Heaven and Hell, you see, I have friends in both places.", a = "Mark Twain", b = "Attributed" },
    { q = "The three great elements of modern civilization: gun powder, printing, and the Protestant religion.", a = "Thomas Carlyle", b = "State of German Literature" },
    { q = "In a market economy, however, the individual has some possibility of escaping from the power of the state.", a = "Peter Berger", b = "The Capitalist Revolution" },
    { q = "Having seen a non-market economy, I suddenly understood much better what I liked about a market economy.", a = "Esther Dyson", b = "Release 2.0" },
    { q = "New opinions are always suspected, and usually opposed, without any other reason but because they are not already common.", a = "John Locke", b = "An Essay Concerning Human Understanding" },
    { q = "Whatever is contrary to nature is contrary to reason, and whatsoever is contrary to reason is absurd.", a = "Baruch Spinoza", b = "Tractatus Theologico-Politicus" },
    { q = "Remember that politics, colonialism, imperialism and war also originated in the human brain.", a = "Vilayanur Ramachandran", b = "The Tell-Tale Brain" },
    { q = "Colonialism. The enforced spread of the rule of reason. But who is going to spread it among the colonizers?", a = "Anthony Burgess", b = "The State of the World" },
    { q = "Improvement makes straight roads; but the crooked roads without improvement are roads of Genius.", a = "William Blake", b = "The Marriage of Heaven and Hell" },
    { q = "A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.", a = "Douglas Adams", b = "Mostly Harmless" },
    { q = "It is nationalism which engenders nations, and not the other way round.", a = "Ernest Gellner", b = "Nations and Nationalism" },
    { q = "Human nature, as manifested in tribalism and nationalism, provides the momentum of the machinery of human evolution.", a = "Arthur Keith", b = "A New Theory of Human Evolution" },
    { q = "Opera is when a guy gets stabbed in the back and, instead of bleeding, he sings.", a = "Robert Benchley", b = "Attributed" },
    { q = "It [ballet] projects a fragile kind of strength and a certain inflexible precision.", a = "Ayn Rand", b = "The Romantic Manifesto" },
    { q = "Had I been present at the Creation, I would have given some useful hints for the better ordering of the universe.", a = "Nelson Algren", b = "Attributed (Originally King Alfonso X)" },
    { q = "In all works on Natural History, we constantly find details of the marvelous adaptation of animals to their food, their habits, and the localities in which they are found.", a = "Alfred Wallace", b = "On the Tendency of Varieties to Depart Indefinitely From the Original Type" },
    { q = "War is hell.", a = "William Tecumseh Sherman", b = "Address to the Michigan Military Academy" },
    { q = "I only understand friendship or scorched earth.", a = "Roger Ailes", b = "Attributed" },
    { q = "It’s the Industrial Revolution and the growth of urban concentrations that led to a sense of anonymity.", a = "Vint Cerf", b = "Interview" },
    { q = "What I like about cities is that everything is king size, the beauty and the ugliness.", a = "Joseph Brodsky", b = "Watermark" },
    { q = "The inherent vice of capitalism is the unequal sharing of blessings; the inherent virtue of socialism is the equal sharing of miseries.", a = "Winston Churchill", b = "House of Commons Speech (1945)" },
    { q = "Always try to rub up against money, for if you rub up against money long enough, some of it may rub off on you.", a = "Damon Runyon", b = "Attributed" },
    { q = "Water and air, the two essentials on which life depends, have become global garbage cans.", a = "Jacques Yves Cousteau", b = "Public Address" },
    { q = "Destroying rainforest for economic gain is like burning a Renaissance painting to cook a meal.", a = "Edward Wilson", b = "Attributed" },
    { q = "The effect of the mass media is not to elicit belief but to maintain the apparatus of addiction.", a = "Christopher Lasch", b = "The Culture of Narcissism" },
    { q = "If you don't read the newspaper, you're uninformed. If you read the newspaper, you're mis-informed.", a = "Mark Twain", b = "Attributed" },
    { q = "When they are preparing for war, those who rule by force speak most copiously about peace until they have completed the mobilization process.", a = "Stefan Zweig", b = "The World of Yesterday" },
    { q = "In order to rally people, governments need enemies … if they do not have a real enemy, they will invent one in order to mobilize us.", a = "Nhat Hanh", b = "Creating True Peace" },
    { q = "The release of atom power has changed everything except our way of thinking…the solution to this problem lies in the heart of mankind. If only I had known, I should have become a watchmaker.", a = "Albert Einstein", b = "Public Statement (1945)" },
    { q = "The children of the nuclear age, I think, were weakened in their capacity to love. Hard to love, when you’re bracing yourself for impact.", a = "Martin Amis", b = "London Fields" },
    { q = "It has been demonstrated that no system, not even the most inhuman, can continue to exist without an ideology.", a = "Joe Slovo", b = "Attributed" },
    { q = "Slowly, ideas lead to ideology, lead to policies that lead to actions.", a = "Nandan Nilekani", b = "Imagining India" },
    { q = "Why is a woman to be treated differently? Woman suffrage will succeed, despite this miserable guerrilla opposition.", a = "Victoria Woodhull", b = "Speech on Women's Suffrage" },
    { q = "Men, their rights, and nothing more; women, their rights, and nothing less.", a = "Susan B. Anthony", b = "The Revolution (Publication Motto)" },
    { q = "Only the mob and the elite can be attracted by the momentum of totalitarianism itself. The masses have to be won by propaganda.", a = "Hannah Arendt", b = "The Origins of Totalitarianism" },
    { q = "The ultimate end of any ideology is totalitarianism.", a = "Tom Robbins", b = "Still Life with Woodpecker" },
    { q = "There’s class warfare, all right, but it’s my class, the rich class, that’s making war … and we’re winning.", a = "Warren Buffett", b = "New York Times Interview (2006)" },
    { q = "The class struggle necessarily leads to the dictatorship of the proletariat.", a = "Karl Marx", b = "Letter to Joseph Weydemeyer (1852)" },
    { q = "From Stettin in the Baltic to Trieste in the Adriatic, an iron curtain has descended across the continent.", a = "Winston Churchill", b = "Sinews of Peace (Iron Curtain Speech)" },
    { q = "The Cold War is not thawing; it is burning with a deadly heat.", a = "Richard Nixon", b = "Public Address" },
    { q = "If winning isn’t everything, why do they keep score?", a = "Vince Lombardi", b = "Attributed" },
    { q = "Sports do not build character. They reveal it.", a = "Heywood Broun", b = "Attributed" },
    { q = "A people without the knowledge of their past history, origin and culture is like a tree without roots.", a = "Marcus Garvey", b = "Attributed" },
    { q = "You don’t stumble upon your heritage. It’s there, just waiting to be explored and shared.", a = "Robbie Robertson", b = "Attributed" },
    { q = "A good plan violently executed right now is far better than a perfect plan executed next week.", a = "George S. Patton", b = "Military Maxims" },
    { q = "Never mind the maneuvers, just go straight at them.", a = "Horatio Nelson", b = "Orders prior to the Battle of Trafalgar" },
    { q = "We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard.", a = "John F. Kennedy", b = "Address at Rice University (1962)" },
    { q = "NASA spent millions of dollars inventing the ball-point pen so they could write in space. The Russians took a pencil.", a = "Will Chabot", b = "Attributed (Urban Legend)" },
    { q = "It has been said that arguing against globalization is like arguing against the laws of gravity.", a = "Kofi Annan", b = "Public Address" },
    { q = "One day there will be no borders, no boundaries, no flags and no countries and the only passport will be the heart.", a = "Carlos Santana", b = "Attributed" },
    { q = "Which of all my important nothings shall I tell you first?", a = "Jane Austen", b = "Letters to Cassandra Austen" },
    { q = "Distracted from distraction by distraction!", a = "T.S. Eliot", b = "Four Quartets: Burnt Norton" },
    { q = "You can never plan the future by the past.", a = "Edmund Burke", b = "Letter to a Member of the National Assembly" },
    { q = "I never think of the future. It comes soon enough.", a = "Albert Einstein", b = "Attributed" },
    { q = "Multitudes, multitudes in the valley of decision: for the day of the Lord is near in the valley of decision.", a = "Joel 3:14", b = "The Bible (KJV)" },
    { q = "I shall return again to the light of the sun, to prepare a home for thy descendants.", a = "Apollonius Rhodius", b = "Argonautica" },
    { q = "We find every where men of mechanical genius, of great general acuteness, and discriminative understanding, who make no scruple in pronouncing the Automaton a pure machine, unconnected with human agency in its movements, and consequently, beyond all comparison, the most astonishing of the inventions of mankind.", a = "Edgar Allen Poe", b = "Maelzel's Chess Player" },
    { q = "Over himself, over his own body and mind, the individual is sovereign.", a = "John Stuart Mill", b = "On Liberty" },
    { q = "Justice is the bond of men in states, for the administration of justice, which is the determination of what is just, is the principle of order in political society.", a = "Aristotle", b = "Politics" },
    { q = "This, O Best Beloved, is another story of the High and Far Off Times.", a = "Rudyard Kipling", b = "Just So Stories" },
    { q = "Ah, my Belovéd, fill the cup that clears To-day of past Regrets and future Fears— To-morrow?—Why, To-morrow I may be Myself with Yesterday’s Sev’n Thousand Years.", a = "Edward FitzGerald", b = "The Rubaiyat of Omar Khayyam" },
    { q = "It has been said aforetime that he who knows both sides has nothing to fear in a hundred fights...", a = "Sun Tzu", b = "The Art of War" },
    { q = "If the enemy know not where he will be attacked, he must prepare in every quarter, and so be everywhere weak.", a = "Sun Tzu", b = "The Art of War" },
    { q = "Fetter this malefactor to the jagged rocks In adamantine bonds infrangible.", a = "Aeschylus", b = "Prometheus Bound" },
    { q = "The time will come and is inevitably coming when all institutions based on force will disappear through their uselessness, stupidity, and even inconvenience becoming obvious to all.", a = "Leo Tolstoy", b = "The Kingdom of God Is Within You" },
}
