-- Quotes from Civilization V and VI (civics and technologies), formatted by
-- Mattson42 (issue 464). Copy this file into settings/bookshelf/quotes to use it.
return {
    { q = "It is not wisdom but authority that makes a law.", a = "Thomas Hobbes", b = "A Dialogue Between a Philosopher and a Student of the Common Laws of England" },
    { q = "At his best, man is the noblest of all animals; separated from law and justice he is the worst.", a = "Aristotle", b = "Politics" },
    { q = "Without craftsmanship, inspiration is a mere reed shaken in the wind.", a = "Johannes Brahms", b = "Personal Correspondence" },
    { q = "Skill without imagination is craftsmanship and gives us many useful objects such as wickerwork picnic baskets.", a = "Tom Stoppard", b = "Artist Descending a Staircase" },
    { q = "Every nation lives by exchanging.", a = "Adam Smith", b = "The Wealth of Nations" },
    { q = "That’s the positive aspect of trade I suppose. The world gets stirred up together.", a = "Isabel Hoving", b = "The Dream Merchant" },
    { q = "Bravery is being the only one who knows you’re afraid.", a = "Colonel David Hackworth", b = "About Face: The Odyssey of an American Warrior" },
    { q = "I don’t underrate the value of military knowledge, but if men make war in slavish obedience to rules, they will fail.", a = "Ulysses S. Grant", b = "Personal Memoirs" },
    { q = "A strong economy begins with a strong, well-educated workforce.", a = "Bill Owens", b = "Public Address" },
    { q = "It is equally important to have a happy and engaged workforce as it is to have a profitable bottom line.", a = "Vern Dosch", b = "Wired Differently" },
    { q = "Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too.", a = "Marcus Aurelius", b = "Meditations" },
    { q = "It was luxuries like air conditioning that brought down the Roman Empire. With air conditioning their windows were shut; they couldn’t hear the barbarians coming.", a = "Garrison Keillor", b = "Lake Wobegon Days" },
    { q = "Mysticism is the mistake of an accidental and individual symbol for a universal one.", a = "Ralph Waldo Emerson", b = "Essays: Second Series" },
    { q = "I like to say I practice militant mysticism. I’m absolutely sure of some things that I don’t quite know.", a = "Rob Bell", b = "Velvet Elvis: Repainting the Christian Faith" },
    { q = "If bread is the first necessity of life, recreation is a close second.", a = "Edward Bellamy", b = "The Duke of Stockbridge" },
    { q = "People who cannot find time for recreation are sooner or later to find time for illness.", a = "John Wanamaker", b = "Public Address" },
    { q = "Politics is the art of the possible, the attainable – the art of the next best.", a = "Otto von Bismarck", b = "Interview with Meyer von Waldeck (1867)" },
    { q = "Divide and rule, a sound motto. Unite and lead, a better one.", a = "Johann Wolfgang von Goethe", b = "Gedichte" },
    { q = "The poets have been mysteriously silent on the subject of cheese.", a = "G. K. Chesterton", b = "Alarms and Discursions" },
    { q = "All the world’s a stage, and all the men and women merely players.", a = "William Shakespeare", b = "As You Like It" },
    { q = "If it’s natural to kill, how come men have to go into training to learn how?", a = "Joan Baez", b = "Daybreak" },
    { q = "Those who in quarrels interpose, must often wipe a bloody nose.", a = "John Gay", b = "Fables" },
    { q = "Invincibility lies in the defense; the possibility of victory in the attack.", a = "Sun Tzu", b = "The Art of War" },
    { q = "Defense is superior to opulence.", a = "Adam Smith", b = "The Wealth of Nations" },
    { q = "I've lived through some terrible things in my life, some of which actually happened.", a = "Mark Twain", b = "Attributed" },
    { q = "History is the version of past events that people have decided to agree upon.", a = "Napoleon Bonaparte", b = "Maxims" },
    { q = "We can no more have exact religious thinking without theology, than exact mensuration and astronomy without mathematics, or exact iron-making without chemistry.", a = "John Hall", b = "Sermon / Public Address" },
    { q = "Man suffers only because he takes seriously what the gods made for fun.", a = "Alan W. Watts", b = "Out of Your Mind" },
    { q = "A good navy is not a provocation to war. It is the surest guaranty of peace.", a = "Theodore Roosevelt", b = "Annual Message to Congress (1902)" },
    { q = "The Navy has both a tradition and a future – and we look with pride and confidence in both directions.", a = "Arleigh Burke", b = "Public Address" },
    { q = "In democracy it’s your vote that counts; in feudalism it’s your count that votes.", a = "Mogens Jallberg", b = "Attributed" },
    { q = "With the advance of feudalism came the growth of iron armor, until, at last, a fighting-man resembled an armadillo.", a = "John Boyle O’Reilly", b = "Attributed" },
    { q = "It’s all papers and forms, the entire civil service is like a fortress made of papers, forms and red tape.", a = "Alexander Ostrovsky", b = "The Diary of a Scoundrel" },
    { q = "The taxpayer - that's someone who works for the federal government but doesn't have to take the civil service examination.", a = "Ronald Reagan", b = "Public Address" },
    { q = "In peace one is despoiled by mercenaries; in war by one’s enemies.", a = "Niccolo Machiavelli", b = "The Prince" },
    { q = "Being a mercenary, though … Hey, we just go wherever there’s a mixture of money and trouble.", a = "Howard Tayler", b = "Schlock Mercenary" },
    { q = "All that glisters is not gold; often have you heard that told.", a = "William Shakespeare", b = "The Merchant of Venice" },
    { q = "There are very honest people who do not think that they have had a bargain unless they have cheated a merchant.", a = "Anatole France", b = "The Crime of Sylvestre Bonnard" },
    { q = "Every man should make his son learn some useful trade or profession, so that in these days of changing fortunes … they may have something tangible to fall back upon.", a = "Phineas T. Barnum", b = "The Art of Money Getting" },
    { q = "You can’t go around arresting the Thieves’ Guild. I mean, we’d be at it all day!", a = "Terry Pratchett", b = "Guards! Guards!" },
    { q = "I conclude then this point touching upon the power of kings with this axiom of divinity, That as to dispute what God may do is blasphemy … so it is sedition to dispute what a king may do.", a = "King James I", b = "Speech to Parliament (1610)" },
    { q = "Listen, strange women lying in ponds distributing swords is no basis for a system of government … You can’t expect to wield supreme power just ‘cause some watery tart threw a sword at you!", a = "Monty Python", b = "Monty Python and the Holy Grail" },
    { q = "The day we stop exploring is the day we commit ourselves to live in a stagnant world, devoid of curiosity, empty of dreams.", a = "Neil deGrasse Tyson", b = "Space Chronicles: Facing the Ultimate Frontier" },
    { q = "We shall not cease from exploration, and the end of all our exploring will be to arrive where we started and know the place for the first time.", a = "T.S. Eliot", b = "Four Quartets: Little Gidding" },
    { q = "The four characteristics of humanism are curiosity, a free mind, belief in good taste, and belief in the human race.", a = "E.M. Forster", b = "Two Cheers for Democracy" },
    { q = "You must not lose faith in humanity. Humanity is like an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.", a = "Mahatma Gandhi", b = "Letter to Rajkumari Amrit Kaur (1941)" },
    { q = "In diplomacy there are two kinds of problems: small ones and large ones. The small ones will go away by themselves, and the large ones you will not be able to do anything about.", a = "Patrick McGuinness", b = "The Last Hundred Days" },
    { q = "A diplomat is a man who always remembers a woman’s birthday but never remembers her age.", a = "Robert Frost", b = "Attributed" },
    { q = "I don't like to commit myself about Heaven and Hell, you see, I have friends in both places.", a = "Mark Twain", b = "Attributed" },
    { q = "The three great elements of modern civilization: gun powder, printing, and the Protestant religion.", a = "Thomas Carlyle", b = "State of German Literature" },
    { q = "In a market economy, however, the individual has some possibility of escaping from the power of the state.", a = "Peter Berger", b = "The Capitalist Revolution" },
    { q = "Having seen a non-market economy, I suddenly understood much better what I liked about a market economy.", a = "Esther Dyson", b = "Release 2.0" },
    { q = "New opinions are always suspected, and usually opposed, without any other reason but because they are not already common.", a = "John Locke", b = "An Essay Concerning Human Understanding" },
    { q = "Whatever is contrary to nature is contrary to reason, and whatsoever is contrary to reason is absurd.", a = "Baruch Spinoza", b = "Tractatus Theologico-Politicus" },
    { q = "Remember that politics, colonialism, imperialism and war also originated in the human brain.", a = "Vilayanur Ramachandran", b = "The Tell-Tale Brain" },
    { q = "Colonialism. The enforced spread of the rule of reason. But who is going to spread it among the colonizers?", a = "Anthony Burgess", b = "The State of the World" },
    { q = "Improvement makes straight roads; but the crooked roads without improvement are roads of Genius.", a = "William Blake", b = "The Marriage of Heaven and Hell" },
    { q = "A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.", a = "Douglas Adams", b = "Mostly Harmless" },
    { q = "It is nationalism which engenders nations, and not the other way round.", a = "Ernest Gellner", b = "Nations and Nationalism" },
    { q = "Human nature, as manifested in tribalism and nationalism, provides the momentum of the machinery of human evolution.", a = "Arthur Keith", b = "A New Theory of Human Evolution" },
    { q = "Opera is when a guy gets stabbed in the back and, instead of bleeding, he sings.", a = "Robert Benchley", b = "Attributed" },
    { q = "It [ballet] projects a fragile kind of strength and a certain inflexible precision.", a = "Ayn Rand", b = "The Romantic Manifesto" },
    { q = "Had I been present at the Creation, I would have given some useful hints for the better ordering of the universe.", a = "Nelson Algren", b = "Attributed (Originally King Alfonso X)" },
    { q = "In all works on Natural History, we constantly find details of the marvelous adaptation of animals to their food, their habits, and the localities in which they are found.", a = "Alfred Wallace", b = "On the Tendency of Varieties to Depart Indefinitely From the Original Type" },
    { q = "War is hell.", a = "William Tecumseh Sherman", b = "Address to the Michigan Military Academy" },
    { q = "I only understand friendship or scorched earth.", a = "Roger Ailes", b = "Attributed" },
    { q = "It’s the Industrial Revolution and the growth of urban concentrations that led to a sense of anonymity.", a = "Vint Cerf", b = "Interview" },
    { q = "What I like about cities is that everything is king size, the beauty and the ugliness.", a = "Joseph Brodsky", b = "Watermark" },
    { q = "The inherent vice of capitalism is the unequal sharing of blessings; the inherent virtue of socialism is the equal sharing of miseries.", a = "Winston Churchill", b = "House of Commons Speech (1945)" },
    { q = "Always try to rub up against money, for if you rub up against money long enough, some of it may rub off on you.", a = "Damon Runyon", b = "Attributed" },
    { q = "Water and air, the two essentials on which life depends, have become global garbage cans.", a = "Jacques Yves Cousteau", b = "Public Address" },
    { q = "Destroying rainforest for economic gain is like burning a Renaissance painting to cook a meal.", a = "Edward Wilson", b = "Attributed" },
    { q = "The effect of the mass media is not to elicit belief but to maintain the apparatus of addiction.", a = "Christopher Lasch", b = "The Culture of Narcissism" },
    { q = "If you don't read the newspaper, you're uninformed. If you read the newspaper, you're mis-informed.", a = "Mark Twain", b = "Attributed" },
    { q = "When they are preparing for war, those who rule by force speak most copiously about peace until they have completed the mobilization process.", a = "Stefan Zweig", b = "The World of Yesterday" },
    { q = "In order to rally people, governments need enemies … if they do not have a real enemy, they will invent one in order to mobilize us.", a = "Nhat Hanh", b = "Creating True Peace" },
    { q = "The release of atom power has changed everything except our way of thinking…the solution to this problem lies in the heart of mankind. If only I had known, I should have become a watchmaker.", a = "Albert Einstein", b = "Public Statement (1945)" },
    { q = "The children of the nuclear age, I think, were weakened in their capacity to love. Hard to love, when you’re bracing yourself for impact.", a = "Martin Amis", b = "London Fields" },
    { q = "It has been demonstrated that no system, not even the most inhuman, can continue to exist without an ideology.", a = "Joe Slovo", b = "Attributed" },
    { q = "Slowly, ideas lead to ideology, lead to policies that lead to actions.", a = "Nandan Nilekani", b = "Imagining India" },
    { q = "Why is a woman to be treated differently? Woman suffrage will succeed, despite this miserable guerrilla opposition.", a = "Victoria Woodhull", b = "Speech on Women's Suffrage" },
    { q = "Men, their rights, and nothing more; women, their rights, and nothing less.", a = "Susan B. Anthony", b = "The Revolution (Publication Motto)" },
    { q = "Only the mob and the elite can be attracted by the momentum of totalitarianism itself. The masses have to be won by propaganda.", a = "Hannah Arendt", b = "The Origins of Totalitarianism" },
    { q = "The ultimate end of any ideology is totalitarianism.", a = "Tom Robbins", b = "Still Life with Woodpecker" },
    { q = "There’s class warfare, all right, but it’s my class, the rich class, that’s making war … and we’re winning.", a = "Warren Buffett", b = "New York Times Interview (2006)" },
    { q = "The class struggle necessarily leads to the dictatorship of the proletariat.", a = "Karl Marx", b = "Letter to Joseph Weydemeyer (1852)" },
    { q = "From Stettin in the Baltic to Trieste in the Adriatic, an iron curtain has descended across the continent.", a = "Winston Churchill", b = "Sinews of Peace (Iron Curtain Speech)" },
    { q = "The Cold War is not thawing; it is burning with a deadly heat.", a = "Richard Nixon", b = "Public Address" },
    { q = "If winning isn’t everything, why do they keep score?", a = "Vince Lombardi", b = "Attributed" },
    { q = "Sports do not build character. They reveal it.", a = "Heywood Broun", b = "Attributed" },
    { q = "A people without the knowledge of their past history, origin and culture is like a tree without roots.", a = "Marcus Garvey", b = "Attributed" },
    { q = "You don’t stumble upon your heritage. It’s there, just waiting to be explored and shared.", a = "Robbie Robertson", b = "Attributed" },
    { q = "A good plan violently executed right now is far better than a perfect plan executed next week.", a = "George S. Patton", b = "Military Maxims" },
    { q = "Never mind the maneuvers, just go straight at them.", a = "Horatio Nelson", b = "Orders prior to the Battle of Trafalgar" },
    { q = "We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard.", a = "John F. Kennedy", b = "Address at Rice University (1962)" },
    { q = "NASA spent millions of dollars inventing the ball-point pen so they could write in space. The Russians took a pencil.", a = "Will Chabot", b = "Attributed (Urban Legend)" },
    { q = "It has been said that arguing against globalization is like arguing against the laws of gravity.", a = "Kofi Annan", b = "Public Address" },
    { q = "One day there will be no borders, no boundaries, no flags and no countries and the only passport will be the heart.", a = "Carlos Santana", b = "Attributed" },
    { q = "Which of all my important nothings shall I tell you first?", a = "Jane Austen", b = "Letters to Cassandra Austen" },
    { q = "Distracted from distraction by distraction!", a = "T.S. Eliot", b = "Four Quartets: Burnt Norton" },
    { q = "You can never plan the future by the past.", a = "Edmund Burke", b = "Letter to a Member of the National Assembly" },
    { q = "I never think of the future. It comes soon enough.", a = "Albert Einstein", b = "Attributed" },
    { q = "Multitudes, multitudes in the valley of decision: for the day of the Lord is near in the valley of decision.", a = "Joel 3:14", b = "The Bible (KJV)" },
    { q = "I shall return again to the light of the sun, to prepare a home for thy descendants.", a = "Apollonius Rhodius", b = "Argonautica" },
    { q = "We find every where men of mechanical genius, of great general acuteness, and discriminative understanding, who make no scruple in pronouncing the Automaton a pure machine, unconnected with human agency in its movements, and consequently, beyond all comparison, the most astonishing of the inventions of mankind.", a = "Edgar Allen Poe", b = "Maelzel's Chess Player" },
    { q = "Over himself, over his own body and mind, the individual is sovereign.", a = "John Stuart Mill", b = "On Liberty" },
    { q = "Justice is the bond of men in states, for the administration of justice, which is the determination of what is just, is the principle of order in political society.", a = "Aristotle", b = "Politics" },
    { q = "This, O Best Beloved, is another story of the High and Far Off Times.", a = "Rudyard Kipling", b = "Just So Stories" },
    { q = "Ah, my Belovéd, fill the cup that clears To-day of past Regrets and future Fears— To-morrow?—Why, To-morrow I may be Myself with Yesterday’s Sev’n Thousand Years.", a = "Edward FitzGerald", b = "The Rubaiyat of Omar Khayyam" },
    { q = "It has been said aforetime that he who knows both sides has nothing to fear in a hundred fights...", a = "Sun Tzu", b = "The Art of War" },
    { q = "If the enemy know not where he will be attacked, he must prepare in every quarter, and so be everywhere weak.", a = "Sun Tzu", b = "The Art of War" },
    { q = "Fetter this malefactor to the jagged rocks In adamantine bonds infrangible.", a = "Aeschylus", b = "Prometheus Bound" },
    { q = "The time will come and is inevitably coming when all institutions based on force will disappear through their uselessness, stupidity, and even inconvenience becoming obvious to all.", a = "Leo Tolstoy", b = "The Kingdom of God Is Within You" },
{ q = "Proud is the spirit of Zeus-fostered kings – their honor comes from Zeus, and Zeus, god of council, loves them.", a = "Homer", b = "The Iliad" },
    { q = "He who knows others is wise; He who knows himself is enlightened.", a = "Lao-tzu", b = "Tao Te Ching" },
    { q = "The king’s might is greater than human, and his arm is very long.", a = "Herodotus", b = "The Histories" },
    { q = "Once the rockets are up, who cares where they come down? That’s not my department, says Wernher von Braun.", a = "Tom Lehrer", b = "Wernher von Braun (Song)" },
    { q = "For tomorrow belongs to the people who prepare for it today.", a = "African Proverb", b = "Traditional Saying" },
    { q = "The future is not what it used to be.", a = "Paul Valéry", b = "Attributed" },
    { q = "I never think about the future. It comes soon enough.", a = "Albert Einstein", b = "Interview (1930)" },
    { q = "If you pick up a starving dog and make him prosperous, he will not bite you. This is the principal difference between a dog and a man.", a = "Mark Twain", b = "Pudd'nhead Wilson" },
    { q = "The day of small nations has long passed away. The day of Empires has come.", a = "Joseph Chamberlain", b = "Speech (1904)" },
    { q = "An emperor is subject to no one but God and Justice.", a = "Frederick I, Barbarossa", b = "Imperial Decree" },
    { q = "This life of man appears for a short space, but of what went before, or what is to follow, we are utterly ignorant.", a = "Venerable Bede", b = "Ecclesiastical History of the English People" },
    { q = "The voice of the people is the voice of God.", a = "Alcuin", b = "Letter to Charlemagne (800 AD)" },
    { q = "The only thing we have to fear is fear itself.", a = "Franklin Delano Roosevelt", b = "First Inaugural Address (1933)" },
    { q = "A single death is a tragedy; a million deaths is a statistic.", a = "Joseph Stalin", b = "Attributed" },
    { q = "Mr. Gorbachev, tear down this wall!", a = "Ronald Reagan", b = "Brandenburg Gate Speech (1987)" },
    { q = "Whoever desires to found a state and give it laws, must start with assuming that all men are bad and ever ready to display their vicious nature, whenever they may find occasion for it.", a = "Niccolò Machiavelli", b = "Discourses on Livy" },
    { q = "In the country of the blind, the one-eyed man is king.", a = "Desiderius Erasmus", b = "Adagia" },
    { q = "Do you not know, my son, with what little understanding the world is ruled?", a = "Pope Julius III", b = "Attributed Remark" },
    { q = "Their rising all at once was as the sound of thunder heard remote.", a = "John Milton", b = "Paradise Lost" },
    { q = "Where tillage begins, other arts follow. The farmers therefore are the founders of human civilization.", a = "Daniel Webster", b = "Remarks on Agriculture (1840)" },
    { q = "Thou shalt not muzzle the ox when he treadeth out the corn.", a = "The Bible", b = "Deuteronomy 25:4" },
    { q = "Those who cannot remember the past are condemned to repeat it.", a = "George Santayana", b = "The Life of Reason" },
    { q = "The haft of the arrow had been feathered with one of the eagle’s own plumes. We often give our enemies the means of our own destruction.", a = "Aesop", b = "Fables" },
    { q = "Joyfully to the breeze royal Odysseus spread his sail, and with his rudder skillfully he steered.", a = "Homer", b = "The Odyssey" },
    { q = "The unleashed power of the atom has changed everything save our modes of thinking, and we thus drift toward unparalleled catastrophes.", a = "Albert Einstein", b = "Telegram to Prominent Americans (1946)" },
    { q = "Happiness: a good bank account, a good cook and a good digestion.", a = "Jean-Jacques Rousseau", b = "Attributed" },
    { q = "If the brain were so simple we could understand it, we would be so simple we couldn’t.", a = "Lyall Watson", b = "The Romeo Error" },
    { q = "Here Hector entered, with a spear eleven cubits long in his hand; the bronze point gleamed in front of him, and was fastened to the shaft of the spear by a ring of gold.", a = "Homer", b = "The Iliad" },
    { q = "In the fall of 1972 President Nixon announced that the rate of increase of inflation was decreasing. This was the first time that a sitting president used the third derivative to advance his case for reelection.", a = "Hugo Rossi", b = "Attributed" },
    { q = "So teach us to number our days, so that we may apply our hearts unto wisdom.", a = "The Bible", b = "Psalms 90:12" },
    { q = "Wherever we look, the work of the chemist has raised the level of our civilization and has increased the productive capacity of the nation.", a = "Calvin Coolidge", b = "Address to the American Chemical Society (1924)" },
    { q = "Whoso pulleth out this sword of this stone and anvil, is rightwise king born of all England.", a = "Sir Thomas Malory", b = "Le Morte d'Arthur" },
    { q = "The only thing that saves us from the bureaucracy is its inefficiency.", a = "Eugene McCarthy", b = "Attributed" },
    { q = "Any man who can drive safely while kissing a pretty girl is simply not giving the kiss the attention it deserves.", a = "Albert Einstein", b = "Attributed" },
    { q = "Computers are like Old Testament gods: lots of rules and no mercy.", a = "Joseph Campbell", b = "The Power of Myth" },
    { q = "Three things are to be looked to in a building: that it stand on the right spot; that it be securely founded; that it be successfully executed.", a = "Johann Wolfgang von Goethe", b = "Elective Affinities" },
    { q = "Better is bread with a happy heart / Than wealth with vexation.", a = "Amenemope", b = "Instruction of Amenemope" },
    { q = "As soon as men decide that all means are permitted to fight an evil, then their good becomes indistinguishable from the evil that they set out to destroy.", a = "Christopher Dawson", b = "The Judgment of the Nations" },
    { q = "Only within the moment of time represented by the present century as one species, man, acquired significant power to alter the nature of his world.", a = "Rachel Carson", b = "Silent Spring" },
    { q = "Compound interest is the most powerful force in the universe.", a = "Albert Einstein", b = "Attributed" },
    { q = "Education is the best provision for old age.", a = "Aristotle", b = "Diogenes Laërtius, Lives of the Eminent Philosophers" },
    { q = "Is it a fact – or have I dreamt it – that, by means of electricity, the world of matter has become a great nerve, vibrating thousands of miles in a breathless point of time?", a = "Nathaniel Hawthorne", b = "The House of the Seven Gables" },
    { q = "There’s a basic principle about consumer electronics: it gets more powerful all the time and it gets cheaper all the time.", a = "Trip Hawkins", b = "Interview" },
    { q = "Instrumental or mechanical science is the noblest and, above all others, the most useful.", a = "Leonardo da Vinci", b = "Notebooks" },
    { q = "The nation that destroys its soil destroys itself.", a = "Franklin Delano Roosevelt", b = "Letter to State Governors (1937)" },
    { q = "Aeronautics was neither an industry nor a science. It was a miracle.", a = "Igor Sikorsky", b = "The Story of the Winged-S" },
    { q = "I think we agree, the past is over.", a = "George W. Bush", b = "Press Conference (2000)" },
    { q = "The new electronic interdependence recreates the world in the image of a global village.", a = "Marshall McLuhan", b = "The Gutenberg Galaxy" },
    { q = "The day when two army corps can annihilate each other in one second, all civilized nations, it is to be hoped, will recoil from war and discharge their troops.", a = "Alfred Nobel", b = "Letter to Bertha von Suttner" },
    { q = "My kingdom for a horse!", a = "William Shakespeare", b = "Richard III" },
    { q = "Do not wait to strike ’til the iron is hot; but make it hot by striking.", a = "William Butler Yeats", b = "Attributed" },
    { q = "The night is far spent, the day is at hand: let us therefore cast off the works of darkness, and let us put on the armor of light.", a = "The Bible", b = "Romans 13:12" },
    { q = "The press is the best instrument for enlightening the mind of man, and improving him as a rational, moral and social being.", a = "Thomas Jefferson", b = "Letter to Thomas Seymour (1807)" },
    { q = "How happy are those whose walls already rise!", a = "Virgil", b = "The Aeneid" },
    { q = "The speed of communications is wondrous to behold. It is also true that speed can multiply the distribution of information that we know to be untrue.", a = "Edward R. Murrow", b = "Address to the RTNDA (1958)" },
    { q = "Mathematics is the gate and key to the sciences.", a = "Roger Bacon", b = "Opus Majus" },
    { q = "When pieces of bronze or gold or iron break, the metal-smith welds them together again in the fire, and the bond is established.", a = "Sri Guru Granth Sahib", b = "Sikh Scripture" },
    { q = "There never was a good knife made of bad steel.", a = "Benjamin Franklin", b = "Poor Richard's Almanack" },
    { q = "Wars may be fought with weapons, but they are won by men. It is the spirit of the men who follow and of the man who leads that gains the victory.", a = "George S. Patton", b = "Cavalry Journal (1933)" },
    { q = "The meek shall inherit the Earth, but not its mineral rights.", a = "J. Paul Getty", b = "Attributed" },
    { q = "The impact of nanotechnology is expected to exceed the impact that the electronics revolution has had on our lives.", a = "Richard Schwartz", b = "Attributed" },
    { q = "The winds and the waves are always on the side of the ablest navigators.", a = "Edward Gibbon", b = "The History of the Decline and Fall of the Roman Empire" },
    { q = "I am become Death, the destroyer of worlds.", a = "J. Robert Oppenheimer", b = "Quoting the Bhagavad Gita" },
    { q = "The release of atomic energy has not created a new problem. It has merely made more urgent the necessity of solving an existing one.", a = "Albert Einstein", b = "Atomic War or Peace (1945)" },
    { q = "He made an instrument to know / If the moon shine at full or no.", a = "Samuel Butler", b = "Hudibras" },
    { q = "Every particle of matter is attracted by or gravitates to every other particle of matter with a force inversely proportional to the squares of their distances.", a = "Isaac Newton", b = "Philosophiae Naturalis Principia Mathematica" },
    { q = "Everything passes – Robust art / Alone is eternal. / The bust / Survives the city.", a = "Théophile Gautier", b = "L'Art" },
    { q = "In nothing do men more nearly approach the gods than in giving health to men.", a = "Cicero", b = "Pro Ligario" },
    { q = "There is only one good, knowledge, and one evil, ignorance.", a = "Socrates", b = "Diogenes Laërtius, Lives of the Eminent Philosophers" },
    { q = "Measure what is measurable, and make measurable what is not so.", a = "Galileo Galilei", b = "Attributed" },
    { q = "Ben, I want to say one word to you, just one word: plastics.", a = "Buck Henry and Calder Willingham", b = "The Graduate (Film)" },
    { q = "Shall the clay say to him that fashioneth it, What makest thou?", a = "The Bible", b = "Isaiah 45:9" },
    { q = "It is a newspaper’s duty to print the news and raise hell.", a = "The Chicago Times", b = "Editorial (1861)" },
    { q = "Vision is the art of seeing things invisible.", a = "Jonathan Swift", b = "Thoughts on Various Subjects" },
    { q = "The whole country was tied together by radio. We all experienced the same heroes and comedians and singers. They were giants.", a = "Woody Allen", b = "Interview" },
    { q = "The introduction of so powerful an agent as steam to a carriage on wheels will make a great change in the situation of man.", a = "Thomas Jefferson", b = "Letter to Charles Willson Peale (1802)" },
    { q = "And homeless near a thousand homes I stood, and near a thousand tables pined and wanted food.", a = "William Wordsworth", b = "Guilt and Sorrow" },
    { q = "Nothing is particularly hard if you divide it into small jobs.", a = "Henry Ford", b = "My Life and Work" },
    { q = "It is well that war is so terrible, or we should grow too fond of it.", a = "Robert E. Lee", b = "Remark at the Battle of Fredericksburg (1862)" },
    { q = "1. A robot may not injure a human being or, through inaction, allow a human being to come to harm. 2. A robot must obey any orders given to it by human beings, except when such orders would conflict with the First Law. 3. A robot must protect its own existence as long as such protection does not conflict with the First or Second Law.", a = "Isaac Asimov", b = "Runaround (Three Laws of Robotics)" },
    { q = "A good rule for rocket experimenters to follow is this: always assume that it will explode.", a = "Astronautics Magazine", b = "1937 Issue" },
    { q = "He who commands the sea has command of everything.", a = "Themistocles", b = "Plutarch's Lives" },
    { q = "Now, somehow, in some new way, the sky seemed almost alien.", a = "Lyndon B. Johnson", b = "Remarks on Sputnik (1957)" },
    { q = "Every great advance in science has issued from a new audacity of imagination.", a = "John Dewey", b = "The Quest for Certainty" },
    { q = "Be extremely subtle, even to the point of formlessness. Be extremely mysterious, even to the point of soundlessness. Thereby you can be the director of the opponent’s fate.", a = "Sun Tzu", b = "The Art of War" },
    { q = "The nations of the West hope that by means of steam communication all the world will become as one family.", a = "Townsend Harris", b = "Journal (1856)" },
    { q = "John Henry said to his Captain, 'A man ain’t nothin’ but a man, And before I’ll let your steam drill beat me down, I’ll die with the hammer in my hand.'", a = "Anonymous", b = "The Ballad of John Henry, the Steel-Drivin’ Man" },
    { q = "I once sent a dozen of my friends a telegram saying ‘flee at once – all is discovered.’ They all left town immediately.", a = "Mark Twain", b = "Attributed" },
    { q = "Wisdom and virtue are like the two wheels of a cart.", a = "Japanese Proverb", b = "Traditional Saying" },
    { q = "Three things are necessary for the salvation of man: to know what he ought to believe; to know what he ought to desire; and to know what he ought to do.", a = "St. Thomas Aquinas", b = "Two Precepts of Charity" },
    { q = "Even brute beasts and wandering birds do not fall into the same traps or nets twice.", a = "Saint Jerome", b = "Letters" },
    { q = "He who destroys a good book kills reason itself.", a = "John Milton", b = "Areopagitica" },
    { q = "The temple is like no other building in the world. It has towers and decoration and all the refinements which the human genius can conceive of.", a = "António da Madalena", b = "Travel Accounts (1586)" },
    { q = "To achieve great things, two things are needed: a plan, and not quite enough time.", a = "Leonard Bernstein", b = "Address to the National Press Club (1980)" },
    { q = "Pale Death beats equally at the poor man’s gate and at the palaces of kings.", a = "Horace", b = "Odes" },
    { q = "The katun is established at Chichen Itza. The settlement of the Itza shall take place there. The quetzal shall come, the green bird shall come. Ah Kantenal shall come. It is the word of God. The Itza shall come.", a = "Mayan Tradition", b = "The Books of Chilam Balam" },
    { q = "Why man, he doth bestride the narrow world like a colossus; and we petty men walk under his huge legs, and peep about to find ourselves dishonorable graves.", a = "William Shakespeare", b = "Julius Caesar" },
    { q = "Come to me, all who labor and are heavy burdened, and I will give you rest.", a = "The Bible", b = "Matthew 11:28" },
    { q = "We live only to discover beauty. All else is a form of waiting.", a = "Kahlil Gibran", b = "Sand and Foam" },
    { q = "Most of us can, as we choose, make of this world either a palace or a prison.", a = "John Lubbock", b = "The Use of Life" },
    { q = "Libraries are as the shrine where all the relics of the ancient saints, full of true virtue, and all that without delusion or imposture are preserved and reposed.", a = "Sir Francis Bacon", b = "The Advancement of Learning" },
    { q = "They that go down to the sea in ships, that do business in great waters; these see the works of the Lord, and his wonders in the deep.", a = "The Bible", b = "Psalms 107:23-24" },
    { q = "The art of war teaches us to rely not on the likelihood of the enemy’s… not attacking, but rather on the fact that we have made our position unassailable.", a = "Sun Tzu", b = "The Art of War" },
    { q = "For it soars to a height to match the sky, and as if surging up from amongst the other buildings it stands on high and looks down upon the remainder of the city, adorning it, because it is a part of it, but glorying in its own beauty.", a = "Procopius", b = "De Aedificis" },
    { q = "I think that if ever a mortal heard the word of God it would be in a garden at the cool of the day.", a = "F. Frankfort Moore", b = "The Jessamy Bride" },
    { q = "Bushido is realized in the presence of death. This means choosing death whenever there is a choice between life and death. There is no other reasoning.", a = "Yamamoto Tsunetomo", b = "Hagakure" },
    { q = "The Law is a fortress on a hill that armies cannot take or floods wash away.", a = "Prophet Muhammad", b = "Hadith / Attributed" },
    { q = "Every genuine work of art has as much reason for being as the earth and the sun.", a = "Ralph Waldo Emerson", b = "Thoughts on Art" },
    { q = "Few romances can ever surpass that of the granite citadel on top of the beetling precipices of Machu Picchu, the crown of Inca Land.", a = "Hiram Bingham", b = "Inca Land" },
    { q = "Architecture has recorded the great ideas of the human race. Not only every religious symbol, but every human thought has its page in that vast book.", a = "Victor Hugo", b = "The Hunchback of Notre-Dame" },
    { q = "The ancient Oracle said that I was the wisest of all the Greeks. It is because I alone, of all the Greeks, know that I know nothing.", a = "Socrates", b = "Plato, Apology" },
    { q = "In preparing for battle I have always found that plans are useless, but planning is indispensible.", a = "Dwight D. Eisenhower", b = "Speech to National Defense Executive Reserve (1957)" },
    { q = "Things always seem fairer when we look back at them, and it is out of that inaccessible tower of the past that Longing leans and beckons.", a = "James Russell Lowell", b = "My Study Windows" },
    { q = "O, let not the pains of death which come upon thee enter into my body. I am the god Tem, and I am in the foremost part of the sky, and the power which protecteth me is that which is with all the gods forever.", a = "Ancient Egyptian (tr. E. A. Wallis Budge)", b = "The Book of the Dead" },
    { q = "I live and love in God’s peculiar light.", a = "Michelangelo Buonarroti", b = "Sonnets" },
    { q = "Give me your tired, your poor, / Your huddled masses yearning to breathe free, / The wretched refuse of your teeming shore. / Send these, the homeless, tempest-tossed to me, / I lift my lamp beside the golden door!", a = "Emma Lazarus", b = "The New Colossus" },
    { q = "Time crumbles things; everything grows old and is forgotten under the power of time.", a = "Aristotle", b = "Physics" },
    { q = "Those who lose dreaming are lost.", a = "Australian Aboriginal Proverb", b = "Traditional Saying" },
    { q = "The Taj Mahal rises above the banks of the river like a solitary tear suspended on the cheek of time.", a = "Rabindranath Tagore", b = "Lover's Gift and Crossing" },
    { q = "More than ever before in human history, we share a common destiny. We can master it only if we face it together. And that is why we have the United Nations.", a = "Kofi Annan", b = "Address to UN General Assembly" },
}
