local root = assert(debug.getinfo(1, "S").source:match("^@(.+)/main%.lua$"))
local Bootstrap = require("orbitui_bootstrap")
local context = Bootstrap.begin(root)
Bootstrap.resolver(context)
require("adapters/orbitui_updates").configure(context)
return dofile(context.runtime .. "/core/orbitui_plugin.lua")
