package.path = "./?.lua;" .. package.path
local H = require("tests/helpers")
local base = os.tmpname()
os.remove(base)
assert(os.execute("mkdir -p " .. base))
local counter = 0
local function write(path, data)
    local f = assert(io.open(path, "wb"))
    assert(f:write(data))
    assert(f:close())
end
local function fixture()
    counter = counter + 1
    local root = base .. "/" .. counter
    assert(os.execute("mkdir -p " .. root .. "/.orbitui-versions/" .. string.rep("a", 64)))
    write(root .. "/VERSION", "0.1.0-alpha.2\n")
    write(root .. "/.orbitui-versions/" .. string.rep("a", 64) .. "/VERSION", "0.1.0-alpha.3\n")
    return dofile("orbitui_bootstrap.lua"), root, string.rep("a", 64)
end
H.test("first install selects factory and makes no activation record", function()
    local B, root = fixture()
    H.eq(B.begin(root).version, "0.1.0-alpha.2")
    B.healthy(root)
    H.eq(B.read(root .. "/.orbitui-active"), nil)
end)
H.test("activation is deferred and never changes the running context", function()
    local B, root, slot = fixture()
    local context = B.begin(root)
    B.activate(root, slot)
    H.eq(context.slot, "factory")
    H.eq(B.begin(root).slot, "factory")
    H.eq(B.state(root).current, slot)
    H.eq(B.state(root).pending, true)
    H.eq(B.metadata(root).version, "0.1.0-alpha.3")
    assert(not pcall(B.activate, root, slot))
end)
H.test("complete restart marks new code healthy and retains rollback", function()
    local B, root, slot = fixture()
    B.begin(root)
    B.activate(root, slot)
    B = dofile("orbitui_bootstrap.lua")
    H.eq(B.begin(root).slot, slot)
    B.healthy(root)
    H.eq(B.state(root).pending, false)
    H.eq(B.state(root).previous, "factory")
    H.eq(B.read(root .. "/.orbitui-booting"), nil)
end)
H.test("interrupted startup restores previous complete version on next launch", function()
    local B, root, slot = fixture()
    B.begin(root)
    B.activate(root, slot)
    B = dofile("orbitui_bootstrap.lua")
    B.begin(root) -- Simulate a process crash before healthy().
    B = dofile("orbitui_bootstrap.lua")
    local context = B.begin(root)
    H.eq(context.slot, "factory")
    assert(context.notice)
    H.eq(B.state(root).previous, "none")
end)
H.test("manual rollback preserves unrelated settings and reader data", function()
    local B, root, slot = fixture()
    write(root .. "/reading-data", "unchanged")
    B.begin(root)
    B.activate(root, slot)
    B = dofile("orbitui_bootstrap.lua")
    B.begin(root)
    B.healthy(root)
    B.rollback(root)
    H.eq(B.state(root).current, "factory")
    H.eq(B.read(root .. "/reading-data"), "unchanged")
    H.eq(B.begin(root).slot, slot)
end)
H.test("pending update can be cancelled without booting it", function()
    local B, root, slot = fixture()
    B.begin(root)
    B.activate(root, slot)
    B.rollback(root)
    H.eq(B.state(root).current, "factory")
    H.eq(B.state(root).pending, false)
end)
H.test("failed activation-record rename leaves the old selection intact", function()
    local B, root, slot = fixture()
    B.begin(root)
    local rename = os.rename
    os.rename = function() return nil, "simulated disk error" end
    local ok = pcall(B.activate, root, slot)
    os.rename = rename
    assert(not ok)
    H.eq(B.state(root).current, "factory")
    H.eq(B.read(root .. "/VERSION"), "0.1.0-alpha.2\n")
end)
H.test("malformed pointers and traversal fail closed", function()
    local B, root = fixture()
    assert(not pcall(B.path, root, "../../outside"))
    write(root .. "/.orbitui-active", "../outside\nfactory\n1\n")
    assert(not pcall(B.begin, root))
    H.eq(B.metadata(root).version, "recovery required")
end)
H.test("oversized activation records fail closed rather than silently selecting factory", function()
    local B, root = fixture()
    write(root .. "/.orbitui-active", string.rep("a", 400))
    assert(not pcall(B.begin, root))
end)
H.test("missing selected VERSION still allows automatic recovery on following launch", function()
    local B, root, slot = fixture()
    B.begin(root)
    B.activate(root, slot)
    os.remove(B.path(root, slot) .. "/VERSION")
    B = dofile("orbitui_bootstrap.lua")
    assert(not pcall(B.begin, root))
    B = dofile("orbitui_bootstrap.lua")
    H.eq(B.begin(root).slot, "factory")
end)
assert(os.execute("rm -rf " .. base))
H.finish()
