-- Generated by scripts/build-ukiyoe.py; museum originals never need runtime networking.
local M = {}
M.pack = "Ukiyo-e Gallery"
M.packs = {
    { name = M.pack, marker = "ornament-ukiyoe-gallery-v1.installed", files = {
        "ATTRIBUTION.txt",
        "Hiroshige - Canary and Wisteria.png",
        "Hiroshige - Fireworks.png",
        "Hiroshige - Kingfisher.png",
        "Hiroshige - Lake Hakone.png",
        "Hiroshige - Mandarin Ducks.png",
        "Hiroshige - Meguro Bridge.png",
        "Hiroshige - Moon Viewing.png",
        "Hiroshige - Night Rain at Karasaki.png",
        "Hiroshige - Pines of Miho.png",
        "Hiroshige - Rain at Shono.png",
        "Hiroshige - Snow at Kambara.png",
        "Hiroshige - Sudden Shower.png",
        "Hokusai - Boat Bridge at Sano.png",
        "Hokusai - Brocade Bridge.png",
        "Hokusai - Great Wave.png",
        "Hokusai - Lake Misaka.png",
        "Hokusai - Ono Waterfall.png",
        "Hokusai - Rain Below the Mountain.png",
        "Hokusai - Red Fuji.png",
        "Hokusai - Rush Gatherer.png",
        "Kuniyoshi - New Yoshiwara.png",
        "Kuniyoshi - Omori.png",
        "README.txt",
        "Sharaku - Fish Seller.png",
        "Sharaku - Ichikawa Ebizo.png",
        "Utamaro - Calligraphy Lesson.png",
        "Utamaro - Cleaning Combs.png",
        "Utamaro - The Flirtatious Type.png",
        "ornaments.json",
        "provenance.json",
        "texture-prompts.json",
        "theme/plank.Hinoki.middle.png",
        "theme/theme.json",
        "theme/wallpaper.jpg",
    } },
}

function M.seed(root, ornaments)
    return require("core/orbitui_ornament_install").seed(root, ornaments.dir(), M.packs)
end

return M
