#!/usr/bin/env python3
"""Import pxlflux's pinned SVG artwork only, never its installer or pack.lua."""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "assets/vector-icons"
spec = importlib.util.spec_from_file_location("vector_build", ROOT / "scripts/build-vector-icons.py")
vector = importlib.util.module_from_spec(spec)
spec.loader.exec_module(vector)

READING = {
    "authors", "bookmark_browser", "collections", "continue", "favorites", "history",
    "library", "random_document", "recent", "series", "tags", "annotations_viewer",
    "bookshelf", "instapaper", "rakuyomi", "records", "streak", "vocabulary_builder", "zlibrary",
}
NAVIGATION = {
    "chevron_left", "chevron_right", "coll_back", "folder", "homescreen", "menu",
    "pager_first", "pager_last", "search", "tab_filebrowser", "tab_navigation",
    "filebrowserplus", "home", "cancel", "close", "exit", "appbar.filebrowser",
    "appbar.menu", "appbar.navigation", "appbar.search",
}
SYSTEM = {
    "frontlight", "night_mode", "power", "settings", "tab_fm_settings", "tab_qs_panel",
    "wifi_toggle", "battery_statistics", "sleep", "time", "usb_storage", "appbar.settings",
    "appbar.contrast", "appbar.rotation", "rotate",
}
ALIASES = {
    "authors": "forfattare", "bookmark_browser": "bokmarken", "collections": "samlingar",
    "continue": "fortsatt lasa", "favorites": "favoriter", "history": "historik",
    "library": "bibliotek", "random_document": "slump bok", "recent": "senaste bocker",
    "series": "serie serier volumes", "tags": "taggar", "annotations_viewer": "anteckningar",
    "bookshelf": "bokhylla bibliotek", "rakuyomi": "manga japanese japanska serier comics",
    "vocabulary_builder": "ord ordforrad", "folder": "mapp", "homescreen": "hem home",
    "search": "sok", "menu": "meny", "frontlight": "belysning ljus",
    "night_mode": "nattlage moon mane", "power": "strom avstangning",
    "settings": "installningar", "wifi_toggle": "natverk", "tab_tools": "verktyg",
    "backup": "sakerhetskopia", "cloud_storage": "moln lagring", "syncthing": "synk sync",
    "ai_assistant": "ai assistent", "stats_calendar": "statistik kalender",
}


def group(name):
    if name in READING or name.startswith(("book.", "bookmark", "dogear.", "star.")):
        return "Reading"
    if name in NAVIGATION or name.startswith(("back.", "chevron.", "control.", "move.", "position.")):
        return "Navigation"
    if name in SYSTEM or name.startswith(("wifi", "rotation.")):
        return "System"
    return "Tools"


def build(repo, output_root=ROOT):
    config = json.loads((BASE / "pxlflux-source.json").read_text())
    commit = config["commit"]
    if not re.fullmatch(r"[0-9a-f]{40}", commit):
        raise ValueError("An exact upstream commit is required")
    files = subprocess.check_output([
        "git", "-C", str(repo), "ls-tree", "-r", "--name-only", "-z", commit,
    ]).decode().split("\0")
    inputs, outputs, pending = {}, {}, {}

    def record(path, data):
        pending[path] = data
        outputs[path] = vector.sha(data)

    for pack, style in config["styles"].items():
        rows, names = [], set()
        for section in config["sections"]:
            directory = f"Solar {style}/{section['directory']} ({style})/"
            selected = sorted(p for p in files if p.startswith(directory) and p.endswith(".svg"))
            if len(selected) != section["count"]:
                raise ValueError(f"Unexpected icon inventory: {directory}")
            for path in selected:
                stem = Path(path).stem
                name = section["prefix"] + "-" + re.sub(r"[^a-z0-9]+", "-", stem.lower()).strip("-")
                if name in names:
                    raise ValueError(f"Duplicate icon identity: {pack}/{name}")
                names.add(name)
                data = vector.git_blob(repo, commit, path)
                inputs[path] = {
                    "git_blob": hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest(),
                    "sha256": vector.sha(data),
                }
                record(f"assets/vector-icons/{pack}/{name}.svg", vector.normalized_svg(data))
                label = stem.replace("_", " ").replace(".", " ").replace("-", " ").title()
                rows.append({"name": name, "label": f"{label} ({section['label']})", "group": group(stem),
                             "aliases": f"{stem} {section['label']} pxlflux {ALIASES.get(stem, '')}"})
        lua = ["-- Generated by scripts/build-solar-pack.py from the pinned pxlflux source.", "return {"]
        for row in rows:
            lua.append("    { " + ", ".join(f"{k} = {json.dumps(v)}" for k, v in row.items()) + " },")
        lua.append("}\n")
        record(f"core/orbitui_{pack.replace('-', '_')}_catalogue.lua", "\n".join(lua).encode())
        print(f"{pack}: {len(rows)} icons")
    license_data = vector.git_blob(repo, commit, "LICENSE")
    inputs["LICENSE"] = {"sha256": vector.sha(license_data)}
    record("assets/vector-icons/PXLFLUX-LICENSE.txt", license_data)
    for path, data in pending.items():
        dest = output_root / path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
    manifest = {"source": config, "inputs": inputs, "outputs": outputs}
    (output_root / "assets/vector-icons/pxlflux-generated.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("repository", type=Path)
    parser.add_argument("--output-root", type=Path, default=ROOT)
    args = parser.parse_args()
    build(args.repository, args.output_root)
