#!/usr/bin/env python3
"""Build the reviewed icon subset offline using fonttools==4.60.1.

Inputs must be the pinned upstream font and codepoints files. Generated assets
share the same static outlines; KOReader needs no variable-font API or network.
"""

import argparse
import hashlib
import json
from pathlib import Path

from fontTools import subset
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets/material-symbols"


def build(font_path, codepoints_path):
    selection = json.loads((ASSETS / "selection.json").read_text())
    for path, key in ((font_path, "font_sha256"), (codepoints_path, "codepoints_sha256")):
        assert hashlib.sha256(path.read_bytes()).hexdigest() == selection[key], f"Unexpected input: {path}"
    codepoints = {name: int(code, 16) for name, code in
                  (line.split() for line in codepoints_path.read_text().splitlines())}
    entries = []
    seen = set()
    for group, names in selection["groups"].items():
        for name in names:
            assert name not in seen, f"Duplicate selection: {name}"
            seen.add(name)
            entries.append({"name": name, "code": codepoints[name], "group": group,
                            "aliases": selection["aliases"].get(name, "")})
    font = TTFont(font_path, recalcTimestamp=False)
    options = subset.Options()
    options.layout_features = []
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
    options.name_legacy = True
    options.name_languages = [0x409]
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes={entry["code"] for entry in entries})
    sub.subset(font)
    font = instantiateVariableFont(font, selection["axes"], inplace=True)
    assert "fvar" not in font
    for name_id, value in {
        1: "OrbitUI Material Symbols Rounded", 2: "Regular",
        3: "OrbitUI-MaterialSymbolsRounded-500-" + selection["upstream_commit"][:12],
        4: "OrbitUI Material Symbols Rounded 500", 6: "OrbitUIMaterialSymbolsRounded500",
    }.items():
        font["name"].setName(value, name_id, 3, 1, 0x409)
    font_path_out = ASSETS / "MaterialSymbolsRounded.ttf"
    font.save(font_path_out)
    units = font["head"].unitsPerEm
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    svg_dir = ASSETS / "icons"
    svg_dir.mkdir(exist_ok=True)
    lua = ["-- Generated by scripts/build-material-icons.py; edit selection.json instead.", "return {"]
    for entry in entries:
        pen = SVGPathPen(glyphs)
        glyphs[cmap[entry["code"]]].draw(pen)
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {units} {units}"'
               f' width="24" height="24"><path fill="#000000"'
               f' transform="translate(0 {units}) scale(1 -1)" d="{pen.getCommands()}"/></svg>\n')
        (svg_dir / (entry["name"] + ".svg")).write_text(svg, encoding="ascii")
        lua.append("    { name = %s, code = 0x%04X, group = %s, aliases = %s }," % (
            json.dumps(entry["name"]), entry["code"], json.dumps(entry["group"]),
            json.dumps(entry["aliases"], ensure_ascii=False)))
    lua.append("}")
    (ROOT / "core/orbitui_material_catalogue.lua").write_text("\n".join(lua) + "\n", encoding="utf-8")
    outputs = {str(path.relative_to(ASSETS)): hashlib.sha256(path.read_bytes()).hexdigest()
               for path in sorted([font_path_out, *svg_dir.glob("*.svg")])}
    assert len(outputs) == len(entries) + 1, "Remove stale generated icons before rebuilding"
    (ASSETS / "generated.json").write_text(json.dumps({"icons": len(entries), "files": outputs}, indent=2) + "\n")
    print(f"Built {len(entries)} icons; static TTF: {font_path_out.stat().st_size} bytes")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("font", type=Path)
    parser.add_argument("codepoints", type=Path)
    args = parser.parse_args()
    build(args.font, args.codepoints)
