#!/usr/bin/env python3
"""Build small offline SVG catalogues from two pinned Git checkouts (stdlib only)."""
import argparse
import hashlib
import json
import re
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "assets/vector-icons"
NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", NS)
PACKS = (("solar-outline", "solar", "Outline"),
         ("solar-duotone", "solar", "Line Duotone"),
         ("tabler", "tabler", None))


def normalized_svg(data):
    if b"<!DOCTYPE" in data or b"<!ENTITY" in data:
        raise ValueError("SVG entities are not allowed")
    svg = ET.fromstring(data)
    if svg.tag != f"{{{NS}}}svg" or svg.get("viewBox") != "0 0 24 24":
        raise ValueError("Expected a 24x24 SVG")
    elements = {"svg", "g", "path", "circle", "ellipse", "rect", "line", "polyline", "polygon"}
    attributes = {"width", "height", "viewBox", "d", "fill", "stroke", "stroke-width",
                  "stroke-linecap", "stroke-linejoin", "stroke-miterlimit", "fill-rule", "clip-rule",
                  "opacity", "fill-opacity", "stroke-opacity", "transform", "cx", "cy", "r",
                  "rx", "ry", "x", "y", "x1", "y1", "x2", "y2", "points"}
    for element in svg.iter():
        if element.tag not in {f"{{{NS}}}{name}" for name in elements}:
            raise ValueError(f"Unsupported SVG element: {element.tag}")
        for key, value in element.attrib.items():
            if key not in attributes or "url(" in value.lower():
                raise ValueError(f"Unsupported SVG attribute: {key}={value}")
            if value == "currentColor":
                element.set(key, "black")
    ET.indent(svg, space="  ")
    return ET.tostring(svg, encoding="utf-8") + b"\n"


def git_blob(repo, commit, path):
    return subprocess.check_output(["git", "-C", str(repo), "show", f"{commit}:{path}"])


def sha(data):
    return hashlib.sha256(data).hexdigest()


def build(solar, tabler):
    selection = json.loads((BASE / "selection.json").read_text())
    repos = {"solar": solar, "tabler": tabler}
    inputs, outputs = {}, {}
    for pack, source, style in PACKS:
        config = selection[source]
        rows, names = [], set()
        dest = BASE / pack
        dest.mkdir(exist_ok=True)
        if source == "solar":
            variant = "outline" if style == "Outline" else "duotone"
            custom = BASE / f"custom/manga-{variant}.svg"
            data = custom.read_bytes()
            inputs[str(custom.relative_to(ROOT))] = {"sha256": sha(data)}
            output = normalized_svg(data)
            (dest / "manga.svg").write_bytes(output)
            outputs[str((dest / "manga.svg").relative_to(ROOT))] = sha(output)
            rows.append(("manga", "Manga (OrbitUI)", "Reading", "manga serier comics japanese japanska hiragana"))
            names.add("manga")
        for group, icons in config["groups"].items():
            for path, aliases in icons:
                name = re.sub(r"[^a-z0-9]+", "-", path.split("/")[-1].lower()).strip("-")
                if name in names:
                    raise ValueError(f"Duplicate icon: {pack}/{name}")
                names.add(name)
                upstream = f"icons/SVG/{style}/{path}.svg" if style else f"icons/outline/{path}.svg"
                data = git_blob(repos[source], config["commit"], upstream)
                blob_id = hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest()
                inputs[f"{source}:{upstream}"] = {"git_blob": blob_id, "sha256": sha(data)}
                output = normalized_svg(data)
                asset = dest / f"{name}.svg"
                asset.write_bytes(output)
                outputs[str(asset.relative_to(ROOT))] = sha(output)
                rows.append((name, path.split("/")[-1].replace("-", " "), group, aliases))
        lua = ["-- Generated by scripts/build-vector-icons.py; edit selection.json, not this file.", "return {"]
        for name, label, group, aliases in rows:
            values = (f"{key} = {json.dumps(value, ensure_ascii=False)}" for key, value in
                      (("name", name), ("label", label), ("group", group), ("aliases", aliases)))
            lua.append("    { " + ", ".join(values) + " },")
        lua.append("}\n")
        catalogue = ROOT / f"core/orbitui_{pack.replace('-', '_')}_catalogue.lua"
        data = "\n".join(lua).encode()
        catalogue.write_bytes(data)
        outputs[str(catalogue.relative_to(ROOT))] = sha(data)
        print(f"{pack}: {len(rows)} icons")
    license_data = git_blob(tabler, selection["tabler"]["commit"], "LICENSE")
    (BASE / "TABLER-LICENSE.txt").write_bytes(license_data)
    outputs["assets/vector-icons/TABLER-LICENSE.txt"] = sha(license_data)
    manifest = {"sources": {k: {a: v[a] for a in ("repository", "commit")} for k, v in selection.items()},
                "inputs": inputs, "outputs": outputs}
    (BASE / "generated.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("solar", type=Path)
    parser.add_argument("tabler", type=Path)
    args = parser.parse_args()
    build(args.solar, args.tabler)
