local map = {}
local files = assert(io.popen("git ls-files --cached --others --exclude-standard components/bookshelf components/simpleui"))
for path in files:lines() do
    local component, relative = path:match("^components/([^/]+)/(.+)%.lua$")
    if component then
        local root = relative:match("^([^/]+)/")
        local include = component == "bookshelf" and (root == "lib" or root == "micromodules")
            or component == "simpleui" and (root == "infra" or root == "engines"
                or root == "features" or root == "screens" or root == "modules"
                or root == "integrations" or relative == "sui_bookshelf_bridge")
        if include then
            assert(not map[relative], "Module collision: " .. relative)
            map[relative] = path
        end
    end
end
assert(files:close())
local keys = {}
for key in pairs(map) do keys[#keys + 1] = key end
table.sort(keys)
local lines = { "-- Generated by scripts/module-map.lua; do not edit by hand.", "return {" }
for _, key in ipairs(keys) do
    lines[#lines + 1] = string.format("    [%q] = %q,", key, map[key])
end
lines[#lines + 1] = "}"
local text = table.concat(lines, "\n") .. "\n"
if arg[1] == "--check" then
    local f = assert(io.open("core/orbitui_module_map.lua", "rb"))
    local existing = f:read("*a")
    f:close()
    assert(existing == text, "Regenerate core/orbitui_module_map.lua before testing or packaging")
    print("Module map: " .. #keys .. " paths verified")
else
    io.write(text)
end
